config/routes.rb
Rails.application.routes.draw do
  resources :feeds do
    collection do
      post :confirm
      get :favorites
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:create, :destroy, :index]

  root to: "users#new"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :feeds
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(feed_id: params[:feed_id])
    redirect_to feeds_path, notice: "#{favorite.feed.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to feeds_path, notice: "#{favorite.feed.user.name}さんのブログをお気に入り解除しました"
  end
  def index
    @favorites = current_user.favorites.all
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[edit update destroy]

  def index
    @feeds = Feed.all
    
  end

  def show
    @favorite = current_user.favorites.find_by(feed_id: @feed.id)
  end

  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def confirm
    @feed = current_user.feeds.build(feed_params)
    render :new if @feed.invalid?
  end

  def edit
    
  end

  def create
    @feed = current_user.feeds.build(feed_params)

    respond_to do |format|
      if @feed.save
        #FeedMailer.feed_mail(@feed).deliver 
        format.html { redirect_to @feed, notice: "Feed was successfully created." }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: "Feed was successfully updated." }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: "Feed was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_feed
    @feed = Feed.find(params[:id])
  end
  
  def feed_params
    params.require(:feed).permit(:content, :image, :image_cache, :user_id)
  end  

  def authenticate_user!
    @feed = Feed.find(params[:id])
    unless current_user.id == @feed.user.id
      flash[:notice] = "権限がないです。"
      redirect_to feeds_path
    end
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def confirm
    @user = current_user.users.build(user_params)
    render :new if @user.invalid?
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "プロフィールを編集しました！"
    else
      render :edit
    end
  end
  def show
    @user = User.find(params[:id])
    @feeds = @user.feeds

    favorites = Favorite.where(user_id: current_user.id).pluck(:feed_id)
    @favorite_list = Feed.find(favorites)
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true, url: choose_new_or_edit) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
        <% feed.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">      
    <%= form.label :content %><br>
    <%= form.text_area :content %><br>
    <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %><br>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <p>Content: <%= @feed.content %></p>
  <br />
  <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %><br>
  <%= form.submit "投稿する" %>
<% end %>
<%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<%
=begin
%>
<p id="notice"><%= notice %></p>
<%
=end
%>

<h1>Feeds</h1>


<%= link_to '写真を投稿する', new_feed_path, class: "btn btn-success"%><br>

<br>
<div class="alert alert-warning" role="alert">みんなの投稿一覧</div>
<table border="1" align="center">
  <thead>
    <tr>
      <th>投稿者</th>
      <th>投稿写真</th>
      <th>内容</th>
      <th>詳細</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.user.name %></td>
        <td class="img"><%= image_tag(feed.image.url) if feed.image.present? %></td>
        <td><%= feed.content %></td>
        <td><%= link_to 'Show', feed, class: "btn btn-primary" %></td>
        <% if feed.user == current_user %>
          <td><%= link_to 'Edit', edit_feed_path(feed), class: "btn btn-warning" %></td>
          <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>


#test

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Image:</strong><br>
  <%= image_tag @feed.image.url if @feed.image.present? %>
</p>

<% unless @feed.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(feed_id: @feed.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %><br>


<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagramclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <ul>
      <li><a href="#">Instagram Clone</a></li>
    </ul>
    </header>
    <br>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id), class: "btn btn-primary" %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <!-- <div class="content"> -->
      <%= yield %>
    <!-- </div> -->

    <footer>
      <p>運営会社Instagram株式会社</p>
      <p>© 2015-2016 Instagram Corp.</p>
    </footer>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true ) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= user.errors.count %> 件のエラーがあります。</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div>
      <%= form.label :名前 %><br>
      <%= form.text_field :name %>
    </div>
    <div>
      <%= form.label :メール %><br>
      <%= form.email_field :email %>
    </div>
    <div>
      <%= form.label :パスワード %><br>
      <%= form.password_field :password %>
    </div>
    <div>
      <%= form.label :パスワード確認 %><br>
      <%= form.password_field :password_confirmation %><br><br>
    </div>
    <div>
      <%= form.label :画像 %><br>
      <%= form.file_field :image %><br>
      <%= form.hidden_field :image_cache %><br>
    </div>
    <div>
      <p><%= form.submit "登録する"%></p>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー情報編集</h1>

<%= render 'form', user: @user %>
<%= link_to 'プロフィール画面へ戻る', user_path(current_user.id) %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :image %>
  <%= f.file_field :image  %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h4><%= link_to 'ユーザー情報を編集する', edit_user_path(@user), class: "btn btn-warning" %></h4>
<%= link_to '写真を投稿する', new_feed_path, class: "btn btn-success"%><br>
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<% if @user.image? %>
  <%= image_tag @user.image.url %>
<% end %>

<% 
=begin %>
# <h1><%= @user.name %>の投稿一覧</h1>
# <table border="1" align="center">
#   <thead>
#     <tr>
#       <th>投稿者</th>
#       <th>内容</th>
#       <th>投稿写真</th>
#       <th>詳細</th>
#       <th>編集</th>
#       <th>削除</th>
#     </tr>
#   </thead>
#   <tbody>
#     <% current_user.feeds.each do |feed| %>
#       <tr>
#         <td><%= feed.user.name %></td>
#         <td><%= feed.content %></td>
#         <td><%= image_tag(feed.image.url) if feed.image && feed.image.url %></td>
#         <td><%= link_to '詳細画面', feed_path(feed.id), class: "btn btn-primary" %></td>
#         <td><%= link_to '編集する', edit_feed_path(feed.id), class: "btn btn-warning" %></td>
#         <td><%= link_to '削除する', feed_path(feed.id), method: :delete, data: { confirm: '本当に削除しますか?' }, class: "btn btn-danger" %></td> 
#       </tr>
#     <% end %>
#   </tbody>
# </table>
# <br>
<% 
=end %>


<h4>お気に入りした写真一覧</h4>
<table border="1" align="center">
  <thead>
  <tr>
    <th>投稿者</th>
    <th>投稿画像</th>
    <th>内容</th>
  </tr>
  </thead>
  <tbody>
  <% if @favorite_list.present? %>
    <% @favorite_list.each do |feed| %>
      <tr>
        <td><%= feed.user.name %></td>
        <td><%= image_tag feed.image.url %></td>
        <td><%= feed.content %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<h4><%= link_to 'みんなの投稿一覧を見る', feeds_path, class: "btn btn-success" %></h4>